export const NOTIFICATION_CATEGORIES = {
  TASK: 'Task',
  PROJECT: 'Project',
  LEAVE: 'Leave',
  ANNOUNCEMENT: 'Announcement'
};

export const NOTIFICATION_COLORS = {
  [NOTIFICATION_CATEGORIES.TASK]: '#A78BFA',
  [NOTIFICATION_CATEGORIES.PROJECT]: '#2BAE9B',
  [NOTIFICATION_CATEGORIES.LEAVE]: '#F6B73C',
  [NOTIFICATION_CATEGORIES.ANNOUNCEMENT]: '#58C27D'
};
